import {
  Link,
  Links,
  LiveReload,
  Meta,
  Outlet,
  useCatch,
  Scripts,
  ScrollRestoration,
} from '@remix-run/react';

import Error from '~/components/util/Error';
import styles from './styles/app.css';

export const meta = () => ({
  charset: 'utf-8',
  title: 'New Remix App',
  viewport: 'width=device-width,initial-scale=1',
});

function Document({ title, children }) {
  return (
    <html lang="en">
      <head>
        <title>{title}</title>
        <Meta />
        <Links />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}

export default function App() {
  return (
    <Document title="eCalendar App">
      <Outlet />
    </Document>
  );
}

// export function CatchBoundary() {
//   const caughtError = useCatch();
//   return (
//     <Document title="An error has occured">
//       <main>
//         <Error title="An error has occured">
//           <p>
//             {/* The Not Found text seen on the front-end is automatically generated by Remix */}
//             {caughtError.data?.message ||
//               'Something went wrong. Please try again later...'}
//           </p>
//           <p>
//             Back to <Link to="/">safety</Link>.
//           </p>
//         </Error>
//       </main>
//     </Document>
//   );
// }

// export function ErrorBoundary({ error }) {
//   const caughtError = useCatch();
//   return (
//     <Document title="An error has occured">
//       <main>
//         <Error title="An error has occured">
//           <p>
//             {/* The Not Found text seen on the front-end is automatically generated by Remix */}
//             {caughtError.data?.message ||
//               'Something went wrong. Please try again later...'}
//           </p>
//           <p>
//             Back to <Link to="/">safety</Link>.
//           </p>
//         </Error>
//       </main>
//     </Document>
//   );
// }

export function links() {
  return [{ rel: 'stylesheet', href: styles }];
}

// TODO: Style the error pages
